src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LivreRepository::class)]
class Livre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 13)]
    private $isbn;

    #[ORM\Column(type: 'string', length: 255)]
    private $titre;

    #[ORM\Column(type: 'decimal', precision: 20, scale: '0', nullable: true)]
    private $nombre_pages;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private $date_de_parution;

    #[ORM\Column(type: 'decimal', precision: 2, scale: '0', nullable: true)]
    private $note;

    #[ORM\ManyToMany(targetEntity: Auteur::class, mappedBy: 'idLivre')]
    private $auteurs;

    #[ORM\ManyToMany(targetEntity: Genre::class, inversedBy: 'livres')]
    private $genres;

    public function __construct()
    {
        $this->auteurs = new ArrayCollection();
        $this->genres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): self
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getNombrePages(): ?string
    {
        return $this->nombre_pages;
    }

    public function setNombrePages(?string $nombre_pages): self
    {
        $this->nombre_pages = $nombre_pages;

        return $this;
    }

    public function getDateDeParution(): ?\DateTimeImmutable
    {
        return $this->date_de_parution;
    }

    public function setDateDeParution(?\DateTimeImmutable $date_de_parution): self
    {
        $this->date_de_parution = $date_de_parution;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(?string $note): self
    {
        $this->note = $note;

        return $this;
    }

    /**
     * @return Collection|Auteur[]
     */
    public function getAuteurs(): Collection
    {
        return $this->auteurs;
    }

    public function addAuteur(Auteur $auteur): self
    {
        if (!$this->auteurs->contains($auteur)) {
            $this->auteurs[] = $auteur;
            $auteur->addIdLivre($this);
        }

        return $this;
    }

    public function removeAuteur(Auteur $auteur): self
    {
        if ($this->auteurs->removeElement($auteur)) {
            $auteur->removeIdLivre($this);
        }

        return $this;
    }

    /**
     * @return Collection|Genre[]
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres[] = $genre;
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        $this->genres->removeElement($genre);

        return $this;
    }
}

src/Form/LivreType.php
<?php

namespace App\Form;

use App\Entity\Livre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LivreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('isbn')
            ->add('titre')
            ->add('nombre_pages')
            ->add('date_de_parution')
            ->add('note')
            ->add('auteurs')
            ->add('genres')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Livre::class,
        ]);
    }
}

src/Controller/LivreController.php
<?php

namespace App\Controller;

use App\Entity\Livre;
use App\Form\LivreType;
use App\Repository\LivreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/livre')]
class LivreController extends AbstractController
{
    #[Route('/', name: 'livre_index', methods: ['GET'])]
    public function index(LivreRepository $livreRepository): Response
    {
        return $this->render('livre/index.html.twig', [
            'livres' => $livreRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'livre_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $livre = new Livre();
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($livre);
            $entityManager->flush();

            return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/new.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'livre_show', methods: ['GET'])]
    public function show(Livre $livre): Response
    {
        return $this->render('livre/show.html.twig', [
            'livre' => $livre,
        ]);
    }

    #[Route('/{id}/edit', name: 'livre_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/edit.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'livre_delete', methods: ['POST'])]
    public function delete(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$livre->getId(), $request->request->get('_token'))) {
            $entityManager->remove($livre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/livre/_delete_form.html.twig
<form method="post" action="{{ path('livre_delete', {'id': livre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ livre.id) }}">
    <button class="btn">Delete</button>
</form>

templates/livre/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/livre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Livre{% endblock %}

{% block body %}
    <h1>Edit Livre</h1>

    {{ include('livre/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('livre_index') }}">back to list</a>

    {{ include('livre/_delete_form.html.twig') }}
{% endblock %}

templates/livre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livre index{% endblock %}

{% block body %}
    {# <h1>Livre index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Isbn</th>
                <th>Titre</th>
                <th>Nombre_pages</th>
                <th>Date_de_parution</th>
                <th>Note</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for livre in livres %}
            <tr>
                <td>{{ livre.id }}</td>
                <td>{{ livre.isbn }}</td>
                <td>{{ livre.titre }}</td>
                <td>{{ livre.nombrePages }}</td>
                <td>{{ livre.dateDeParution ? livre.dateDeParution|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ livre.note }}</td>
                <td>
                    <a href="{{ path('livre_show', {'id': livre.id}) }}">show</a>
                    <a href="{{ path('livre_edit', {'id': livre.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('livre_new') }}">Create new</a> #}
    <section class="snew">
		<div class="new-container">
            <!-- Box -->
            {% for key,livre in livres %}
            <div class="box">
                <div class="box-img">
                    <img src="../images/b{{key%4+1}}.jpg" alt="">
                </div>
                <div class="title-price">
                    <h3>{{ livre.titre }}</h3>
                    <div class="stars">
                        {% set nb = livre.note %}
                        {% if (nb  / 5)%10 != 0 %}
                        {% for i in 1..(nb  / 5)%10 %}
                            <i class="bx bxs-star"></i>
                        {% endfor %}
                        {% endif %}
                        {% if ((nb / 5) - (nb / 5)%10)*10 >= 5 %}
                        <i class="bx bxs-star-half"></i>
                        {% else %}
                        <i class="bx bx-star"></i>
                        {% endif %}
                        {% if (4 - (nb / 5)%10) != 0 %}
                        {% for i in 1..((4 - (nb / 5)%10)) %}
                            <i class="bx bx-star"></i>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <span>{{ livre.nombrePages }} pages</span><br>
                <span>{{ livre.dateDeParution ? livre.dateDeParution|date('Y-m-d') : '' }}</span>
                <i class='bx bx-right-arrow' ></i>
            </div>
            {% endfor %}
		</div>
	</section>
{% endblock %}

templates/livre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Livre{% endblock %}

{% block body %}
    <h1>Create new Livre</h1>

    {{ include('livre/_form.html.twig') }}

    <a href="{{ path('livre_index') }}">back to list</a>
{% endblock %}

templates/livre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livre{% endblock %}

{% block body %}
    <h1>Livre</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ livre.id }}</td>
            </tr>
            <tr>
                <th>Isbn</th>
                <td>{{ livre.isbn }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ livre.titre }}</td>
            </tr>
            <tr>
                <th>Nombre_pages</th>
                <td>{{ livre.nombrePages }}</td>
            </tr>
            <tr>
                <th>Date_de_parution</th>
                <td>{{ livre.dateDeParution ? livre.dateDeParution|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Note</th>
                <td>{{ livre.note }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('livre_index') }}">back to list</a>

    <a href="{{ path('livre_edit', {'id': livre.id}) }}">edit</a>

    {{ include('livre/_delete_form.html.twig') }}
{% endblock %}