src/Entity/Auteur.php
<?php

namespace App\Entity;

use App\Repository\AuteurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AuteurRepository::class)]
class Auteur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom_prenom;

    #[ORM\Column(type: 'string', length: 1, nullable: true)]
    private $sexe;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private $date_de_naissance;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $nationalite;

    #[ORM\ManyToMany(targetEntity: Livre::class, inversedBy: 'auteurs')]
    private $idLivre;

    public function __construct()
    {
        $this->idLivre = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomPrenom(): ?string
    {
        return $this->nom_prenom;
    }

    public function setNomPrenom(string $nom_prenom): self
    {
        $this->nom_prenom = $nom_prenom;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(?string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeImmutable
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(?\DateTimeImmutable $date_de_naissance): self
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(?string $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    /**
     * @return Collection|Livre[]
     */
    public function getIdLivre(): Collection
    {
        return $this->idLivre;
    }

    public function addIdLivre(Livre $idLivre): self
    {
        if (!$this->idLivre->contains($idLivre)) {
            $this->idLivre[] = $idLivre;
        }

        return $this;
    }

    public function removeIdLivre(Livre $idLivre): self
    {
        $this->idLivre->removeElement($idLivre);

        return $this;
    }
}

src/Form/AuteurType.php
<?php

namespace App\Form;

use App\Entity\Auteur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AuteurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_prenom')
            ->add('sexe')
            ->add('date_de_naissance')
            ->add('nationalite')
            ->add('idLivre')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Auteur::class,
        ]);
    }
}

src/Controller/AuteurController.php
<?php

namespace App\Controller;

use App\Entity\Auteur;
use App\Form\AuteurType;
use App\Repository\AuteurRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/auteur')]
class AuteurController extends AbstractController
{
    #[Route('/', name: 'auteur_index', methods: ['GET'])]
    public function index(AuteurRepository $auteurRepository): Response
    {
        return $this->render('auteur/index.html.twig', [
            'auteurs' => $auteurRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'auteur_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $auteur = new Auteur();
        $form = $this->createForm(AuteurType::class, $auteur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($auteur);
            $entityManager->flush();

            return $this->redirectToRoute('auteur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('auteur/new.html.twig', [
            'auteur' => $auteur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'auteur_show', methods: ['GET'])]
    public function show(Auteur $auteur): Response
    {
        return $this->render('auteur/show.html.twig', [
            'auteur' => $auteur,
        ]);
    }

    #[Route('/{id}/edit', name: 'auteur_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Auteur $auteur, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AuteurType::class, $auteur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('auteur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('auteur/edit.html.twig', [
            'auteur' => $auteur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'auteur_delete', methods: ['POST'])]
    public function delete(Request $request, Auteur $auteur, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$auteur->getId(), $request->request->get('_token'))) {
            $entityManager->remove($auteur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('auteur_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/auteur/_delete_form.html.twig
<form method="post" action="{{ path('auteur_delete', {'id': auteur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ auteur.id) }}">
    <button class="btn">Delete</button>
</form>

templates/auteur/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/auteur/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Auteur{% endblock %}

{% block body %}
    <h1>Edit Auteur</h1>

    {{ include('auteur/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('auteur_index') }}">back to list</a>

    {{ include('auteur/_delete_form.html.twig') }}
{% endblock %}

templates/auteur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Auteur index{% endblock %}

{% block body %}
    {# <h1>Auteur index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_prenom</th>
                <th>Sexe</th>
                <th>Date_de_naissance</th>
                <th>Nationalite</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for auteur in auteurs %}
            <tr>
                <td>{{ auteur.id }}</td>
                <td>{{ auteur.nomPrenom }}</td>
                <td>{{ auteur.sexe }}</td>
                <td>{{ auteur.dateDeNaissance ? auteur.dateDeNaissance|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ auteur.nationalite }}</td>
                <td>
                    <a href="{{ path('auteur_show', {'id': auteur.id}) }}">show</a>
                    <a href="{{ path('auteur_edit', {'id': auteur.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table> #}

    {# <a href="{{ path('auteur_new') }}">Create new</a> #}

    <section class="snew">
		<div class="new-container">
            <!-- Box -->
            {% for key,auteur in auteurs %}
            <div class="box">
                <div class="box-img">
                    <img src="../images/a{{key%5+1}}.jpg" alt="">
                </div>
                <div class="title-price">
                    <h3>{{ auteur.nomPrenom }}</h3>
                </div>
                <span>{{ auteur.nationalite }}</span>
                <i class='bx bx-right-arrow' ></i>
            </div>
            {% endfor %}
		</div>
	</section>
{% endblock %}

templates/auteur/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Auteur{% endblock %}

{% block body %}
    <h1>Create new Auteur</h1>

    {{ include('auteur/_form.html.twig') }}

    <a href="{{ path('auteur_index') }}">back to list</a>
{% endblock %}

templates/auteur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Auteur{% endblock %}

{% block body %}
    <h1>Auteur</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ auteur.id }}</td>
            </tr>
            <tr>
                <th>Nom_prenom</th>
                <td>{{ auteur.nomPrenom }}</td>
            </tr>
            <tr>
                <th>Sexe</th>
                <td>{{ auteur.sexe }}</td>
            </tr>
            <tr>
                <th>Date_de_naissance</th>
                <td>{{ auteur.dateDeNaissance ? auteur.dateDeNaissance|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Nationalite</th>
                <td>{{ auteur.nationalite }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('auteur_index') }}">back to list</a>

    <a href="{{ path('auteur_edit', {'id': auteur.id}) }}">edit</a>

    {{ include('auteur/_delete_form.html.twig') }}
{% endblock %}